apiVersion: apps/v1
kind: Deployment
metadata:
  name: test002
  labels:
    app: test002
  namespace: namespace-workflow-1704384513958
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test002
  template:
    metadata:
      labels:
        app: test002
    spec:
      containers:
        - name: test002
          image: testcanipull.azurecr.io/image-workflow-1704384513958:latest
          ports:
            - containerPort: 80