apiVersion: v1
kind: Service
metadata:
  name: testaaa
  namespace: namespace-workflow-1709752314760
spec:
  type: LoadBalancer
  selector:
    app: testaaa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80